# Generated by Django 3.1.7 on 2021-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание товара')),
                ('categories', models.CharField(choices=[('food', 'еда'), ('household_products', 'бытовые товары'), ('garden_staff', 'товары для огорода'), ('other', 'разное')], default='other', max_length=50, verbose_name='категория')),
                ('remainder', models.PositiveIntegerField(verbose_name='остаток')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='стоимость')),
            ],
        ),
    ]
